/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/entrypoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_entrypoints"];
        put?: never;
        post: operations["create_entrypoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entrypoints/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_entrypoint"];
        put?: never;
        post?: never;
        delete: operations["delete_entrypoint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_layers"];
        put?: never;
        post: operations["create_layer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_layer"];
        put?: never;
        post?: never;
        delete: operations["delete_layer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{id}/mount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mount_layer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{id}/unmount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unmount_layer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/remount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["system_remount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["system_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-mounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_user_mounts"];
        put?: never;
        post: operations["create_user_mount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-mounts/attach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["attach_layer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-mounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_user_mount"];
        put?: never;
        post?: never;
        delete: operations["delete_user_mount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-mounts/{id}/mount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mount_user_mount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-mounts/{id}/unmount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unmount_user_mount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AttachLayerRequest: {
            /** Format: uuid */
            layerId?: string | null;
            /** Format: uuid */
            userMountId: string;
        };
        CreateEntrypointRequest: {
            name: string;
            path: string;
        };
        CreateLayerRequest: {
            /** Format: uuid */
            entrypointId: string;
            mountPath?: string | null;
            name: string;
            /** Format: uuid */
            parentId?: string | null;
        };
        CreateUserMountRequest: {
            /** Format: uuid */
            attachedLayerId?: string | null;
            /** Format: uuid */
            entrypointId: string;
            mountPath: string;
            name: string;
        };
        Entrypoint: {
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            name: string;
            path: string;
            /** Format: date-time */
            updatedAt: string;
        };
        FileChange: {
            changeType: components["schemas"]["FileChangeType"];
            relativePath: string;
            /** Format: int32 */
            sourceGid: number;
            /** Format: int32 */
            sourceUid: number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @enum {string} */
        FileChangeType: "add" | "modify" | "delete";
        HealthResponse: {
            status: string;
        };
        Layer: {
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            entrypointId: string;
            /** Format: uuid */
            id: string;
            mountPath: string;
            name: string;
            /** Format: uuid */
            parentId?: string | null;
            /** Format: date-time */
            updatedAt: string;
            upperDir: string;
            workDir: string;
        };
        LayerResponse: {
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            entrypointId: string;
            /** Format: uuid */
            id: string;
            mountPath: string;
            mountStatus: components["schemas"]["MountStatus"];
            name: string;
            /** Format: uuid */
            parentId?: string | null;
            /** Format: date-time */
            updatedAt: string;
            upperDir: string;
            workDir: string;
        };
        ListQuery: {
            /** Format: uuid */
            entrypointId?: string | null;
        };
        /** @enum {string} */
        MountStatus: "mounted" | "unmounted" | "error";
        StatusResponse: {
            entrypointCount: number;
            layerCount: number;
            mountedLayers: number;
            mountedUserMounts: number;
            userMountCount: number;
        };
        SyncState: {
            error?: string | null;
            /** Format: date-time */
            lastSyncedAt?: string | null;
            pendingChanges: components["schemas"]["FileChange"][];
            status: components["schemas"]["SyncStatus"];
            /** Format: uuid */
            userMountId: string;
        };
        /** @enum {string} */
        SyncStatus: "idle" | "syncing" | "error";
        UserMount: {
            /** Format: uuid */
            attachedLayerId?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            entrypointId: string;
            /** Format: uuid */
            id: string;
            mountPath: string;
            name: string;
            /** Format: date-time */
            updatedAt: string;
            upperDir: string;
            workDir: string;
        };
        UserMountResponse: {
            /** Format: uuid */
            attachedLayerId?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            entrypointId: string;
            /** Format: uuid */
            id: string;
            mountPath: string;
            mountStatus: components["schemas"]["MountStatus"];
            name: string;
            syncState?: components["schemas"]["SyncState"] | null;
            /** Format: date-time */
            updatedAt: string;
            upperDir: string;
            workDir: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_entrypoints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entrypoint"][];
                };
            };
        };
    };
    create_entrypoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntrypointRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entrypoint"];
                };
            };
        };
    };
    get_entrypoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entrypoint ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entrypoint"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_entrypoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entrypoint ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_layers: {
        parameters: {
            query?: {
                entrypointId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerResponse"][];
                };
            };
        };
    };
    create_layer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLayerRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerResponse"];
                };
            };
        };
    };
    get_layer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Layer ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_layer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Layer ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mount_layer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Layer ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unmount_layer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Layer ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    system_remount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    system_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    list_user_mounts: {
        parameters: {
            query?: {
                entrypointId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMountResponse"][];
                };
            };
        };
    };
    create_user_mount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserMountRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMountResponse"];
                };
            };
        };
    };
    attach_layer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachLayerRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_user_mount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User mount ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMountResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_user_mount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User mount ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mount_user_mount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User mount ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unmount_user_mount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User mount ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
